### ISSUE TITLE
Enable auto-label bot to mark stale pull requests

### ISSUE THREAD

**Issue by losalex** [googleapis/java-logging#757]
**Is your feature request related to a problem? Please describe.**
Need to enable auto-label bot to mark stale PRs to help prioritize old issues

**Describe the solution you'd like**
Add .github/auto-label.yaml with following config:
```yml
product: true
staleness:
  pullrequest: true
  old: 30
  critical: 60
```

**Describe alternatives you've considered**
None

**Additional context**
There was a check in [#2906](https://github.com/googleapis/repo-automation-bots/pull/2906) which enables stale PRs tracking
